PROGRAM_DATA_DIR = 'cash'
PUBLIC_DATA_DIR = '../../../data'
CLOUD_DATA_DIR = 'reaktorBackup'
WORKING_FILE_PATH = 'cash/data.xlsx'
PUBLIC_FILE_PATH = '../../../data/data.xlsx'
CLOUD_TOKEN_PATH = 'cloud/token.json'
CLOUD_CREDENTIALS_PATH = 'cloud/credentials.json'
