class Constants:
    CONFIGURATION_FILE_PATH = '../../data/configuration.txt'
    MIN_DASHBOARD_UPDATE_INTERVAL = 5
    MAX_DASHBOARD_UPDATE_INTERVAL = 86400 # 1 day
    MIN_DATA_FILE_UPDATE_INTERVAL = 5
    MAX_DATA_FILE_UPDATE_INTERVAL = 604800 # 1 week
